### ISSUE TITLE
'cnmf_refit.estimates.detrend_df_f' in demo_pipeline.ipynb requires tons of memory?

### ISSUE THREAD

**Issue by brian-arnold** [flatironinstitute/CaImAn#1274] opened 2024-02-13 19:56 UTC
Please fill in the following for any issues

Your setup:
Repeatable on both my university's computing cluster and my Mac laptop

 1. Operating System (Linux, MacOS, Windows):
- Linux and MacOS (14.2)

 2. Hardware type (x86, ARM..) and RAM:
- Hardware: x86 and ARM 
- RAM: 150GB+ on computing cluster, 96GB on Mac

 3. Python Version (e.g. 3.9):
 - 3.11.7

4. Caiman version (e.g. 1.9.12):
- 1.10.2 

5. Which demo exhibits the problem (if applicable):
 - demo_pipeline.ipynb, ran cell by cell without making any changes, using the data provided by the tutorial: download_demo('Sue_2x_3000_40_-46.tif')

6. How you installed Caiman (pure conda, conda + compile, colab, ..):
- conda, but for my MAC I had to additionally 'pip install tensorflow-macos' to get the following command to run:
cnmf_refit.estimates.evaluate_components

7. Details: 

Thank you for such a fabulous set of well-documented tools!

I'm running demo_pipeline.ipynb, using data provided by the demo, and all but one cell in the notebook works like a charm, both when I run the jupyter notebook (via VS Code) interactively on our computing cluster with lots of memory and my Mac, which also has a decent amount of memory. 

However, every time I reach the cell containing the function that computes delta_f/f (using cnmf_refit.estimates.detrend_df_f), the kernel crashes. I suspect it's a memory issue because when I monitor memory consumption on our computing cluster using 'top', over the course of ~15 min memory usage gradually increases to ~200GB before it hits 0 and the kernel crashes. Likewise, on my Mac with 96GB of memory, after 15 min it says the application ran out of memory.

Are there any options or parameters I can change to help this? Or is the only solution to just get more memory? We have some large datasets we want to analyze, so I worry that if I'm hitting memory issues with the demo data that I will certainly encounter this issue on the data we're interested in.

Thanks for any help or advice!
Brian

**Comment by EricThomson** [comment] 2024-02-13 22:39
Yikes that's not good. This is a _relatively_ simple calculation that shouldn't require that much memory. Let me try to reproduce soon: we've started to adjust things around that method recently (see #1260 ). I should be able to get to it tomorrow.

**Comment by kushalkolar** [comment] 2024-02-14 03:06
What if you give `use_residuals=False` ?

**Comment by brian-arnold** [comment] 2024-02-14 03:30
I had `use_residuals=False` since it's specified that way in the demo_pipeline.ipynb notebook (although I see the default behavior is True).

**Comment by restrepd** [comment] 2024-02-14 09:35
I was the person that filed https://github.com/nel-lab/mesmerize-core/issues/276 in mesmerize. I gave use_residuals=False, and ran get_detrend_dfof and I still get the same problem. I agree that this is a simple calculation and should not require much memory leading to a crash. Here is a screenshot with nvtop. I suppose I could work around this by running the old matlab code exxtract_DF_F.m.
<img width="1369" alt="Screenshot 2024-02-14 at 2 24 02 AM" src="https://github.com/flatironinstitute/CaImAn/assets/109797320/876bf45a-9279-4916-8214-d44fe6b527e8">
Thanks!

**Comment by kushalkolar** [comment] 2024-02-14 10:07
@restrepd That's your GPU VRAM not your system RAM. Caiman doesn't use the GPU.

**Comment by EricThomson** [comment] 2024-02-14 13:29
Yep this is #1262 . Ummm....avoid `use_residuals=False` right now this is the infinite while loop bug 😬 .  I will start the fix on this today or asap this is pretty urgent.  It has to do with some deprecations from scipy that we need to accommodate. Sorry about this. We are exposing things that have been hidden for a while in dff, so bugs are getting exposed and I need to fix them.

**Comment by restrepd** [comment] 2024-02-14 13:52
Thanks a bunch!

**Comment by restrepd** [comment] 2024-02-14 15:38
Thanks! It works!

**Comment by EricThomson** [comment] 2024-02-14 15:56
Just to clarify: it isn't taking tons of memory because it is a memory intensive computation, but because you are sucked into an infinite while loop. I will work on fixing this my guess is within a week, so people can once again use `flag_auto`. Please see [programmer time translation guide](https://coding.abel.nu/2012/06/programmer-time-translation-table/).  😄

**Comment by brian-arnold** [comment] 2024-02-14 17:15
Also confirming that setting `use_residuals=True` and `flag_auto=False` makes everything work!

**Comment by EricThomson** [comment] 2024-02-14 20:38
Just to clarify, as I was a bit murky above: it should work with either value of `use_residuals` as long as `flat_auto` is set to `False`.

**Comment by EricThomson** [comment] 2024-03-22 16:22
This is fixed as of #1288 the different permutations of dff calculation should now work (I think it is merged into main so should be part of conda install now).

**Closed by EricThomson** 2024-03-22 16:22 UTC
Labels: type: bug
