### ISSUE TITLE
conda install caiman fails due to unspecified Python version

### ISSUE THREAD

**Issue by HagaiHargil** [flatironinstitute/CaImAn#632] opened 2019-08-19 11:39 UTC
I tried installing the latest version of `CaImAn` using `conda install -c conda-forge caiman`, but received the following error:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - caiman -> mypy -> python >=3.5,<3.6.0a0
  - python 2.7*
```
I went to the [feedstock repo](https://github.com/conda-forge/caiman-feedstock/blob/master/recipe/meta.yaml) and saw that the Python version isn't specified there. I was indeed trying to install `CaImAn` on a CentOS 7 workstation, which defaults to Python 2.7, using a Python 2 miniconda installation.

I believe that specifying the exact Python version to install, like how it's done in this repo's `environment.yml`, would solve the issue.

Thanks!

**Comment by epnev** [comment] 2019-08-19 13:38
oh boy.. @pgunn can you pin python to >= 3.6?

**Comment by pgunn** [comment] 2019-08-19 14:00
(our instructions tell you to use miniconda3 rather than miniconda2, but if you already have a python2-focused conda this is reasonable concern)
I'll look into pinning it there.

**Comment by HagaiHargil** [comment] 2019-08-19 14:03
@pgunn Sadly I can't modify the installation of `miniconda` at this workstation - it's not our server and I don't have admin privileges, so I'm kinda stuck.

**Comment by pgunn** [comment] 2019-08-19 15:13
HagaiHargil: I chatted with the conda-forge people on this, and if we do that pinning, you'll just get a slight variant on that error (the issue is you're either working from miniconda2's base environment, which is pinned to python2, or you made a new environment under it that's also pined to python2).

What you'll need to do is make a new environment without that pin. Namely:

`conda create -n caiman -c conda-forge caiman python=3.7`

Please do not install caiman into your base environment.

Cheers,
Pat

**Comment by zbarry** [comment] 2019-08-19 15:24
Hey @HagaiHargil - don't have a lot of info on your setup of course, but I have a feeling you can just download your own miniconda into your home folder and add it to your personal path in your `.bashrc`. There's not really any installation that happens via this method. You're basically doing the equivalent of unzipping a folder. No admin required at all.

**Comment by HagaiHargil** [comment] 2019-08-20 18:17
Hi @zbarry, thank you for your suggestions.

I'm aware of your proposed solution, and have tried it in the past. The situation is more complicated than what I described due to the fact that several researchers, most of whom are not command line ninjas, have to work on the same user. Having two `conda`s on that workstation caused issues which are not easy to resolve if you have no previous experience with either conda or the linux command line.

Regardless of our malfunctioning permission and user system, I believe you'll agree with me that not pinning your dependencies is an anti-pattern. This is true for all libraries you use in all languages, and especially true for your Python version. Some languages actually go the distance and disallow you from *not* pinning the dependencies of the libraries you use. That's why I think that this issue should be resolved independently of my (quite faulty) use case.

**Comment by pgunn** [comment] 2019-08-20 18:26
Hagai: We're following conda-forge best practices with the way we're doing it now - I checked in with the conda-forge maintainers and the restriction in the build section is the way they suggest packages in conda-forge specify this. I'm not inclined to go against their advice.

In the meantime, you will be able to likely get Caiman working through conda by creating a new environment as follows:

`conda create -n caiman -c conda-forge caiman python=3.7`

You probably should not try to install the package into an existing environment (especially the base environment) because you might accidentally pull the version of python up to 3.x and break anything else you installed into that environment (or likely conda itself).

Cheers,
Pat

**Closed by pgunn** 2019-08-20 18:26 UTC

**Comment by epnev** [comment] 2019-08-20 20:51
@HagaiHargil I think one can argue both in favor and against pinning. We have decided to refrain from it to reduce the maintaining load and also give users the freedoms to install additional packages in their environments without too many constraints. We're willing to reconsider this decision if the number of problems that arise (e.g. from bad builds of dependencies) becomes too high. So far, it's controllable.

**Comment by HagaiHargil** [comment] 2019-08-21 02:33
Thank you both @pgunn @epnev for taking the time to consider this issue.
