### ISSUE TITLE
cnm.fit(Y) in the CNMF-E demo pipeline

### ISSUE THREAD

**Issue by dprotter** [flatironinstitute/CaImAn#255] opened 2018-05-20 17:57 UTC
For better support, please use the template below to submit your issue.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

- **Tell us about your operating system (Linux/macOS/Windows) and Python version (2.7/3.x)**
Mac OS, Python 3.6

- **Describe the issue that you are experiencing**
I've been trying the CNMF-E demo pipeline. Works great with the demo data. However, I can't get my own data to fit. It occurs during cnm.fit(Y)

- **Copy error log below**

(2001, 128, 128)
using 24 processes
using 4000 pixels per process
using 5000 block_size
(80, 80)
4
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/davidprotter/anaconda/envs/caiman/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/davidprotter/anaconda/envs/caiman/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/davidprotter/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 154, in cnmf_patches
    cnm = cnm.fit(images)
  File "/Users/davidprotter/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 451, in fit
    Y, sn=sn, options_total=options, **options['init_params'])
  File "/Users/davidprotter/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 351, in initialize_components
    sn=sn, nb=nb, ssub=ssub, ssub_B=ssub_B, compute_B_3x=compute_B_3x, init_iter=init_iter)
  File "/Users/davidprotter/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 1017, in greedyROI_corr
    A, C, (d1, d2), ring_size_factor * gSiz, ssub=ssub_B)
  File "/Users/davidprotter/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 1635, in compute_W
    downscale(C, (1, tsub))) - \
ValueError: cannot reshape array of size 0 into shape (0)
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-27-f71fe2c88b8b> in <module>()
     24                 del_duplicates=True)                    # whether to remove duplicates from initialization
     25 
---> 26 cnm.fit(Y)

~/CaImAn/caiman/source_extraction/cnmf/cnmf.py in fit(self, images)
    560                                                                      gnb=self.gnb, border_pix=self.border_pix,
    561                                                                      low_rank_background=self.low_rank_background,
--> 562                                                                      del_duplicates=self.del_duplicates)
    563 
    564             # options = CNMFSetParms(Y, self.n_processes, p=self.p, gSig=self.gSig, K=A.shape[

~/CaImAn/caiman/source_extraction/cnmf/map_reduce.py in run_CNMF_patches(file_name, shape, options, rf, stride, gnb, dview, memory_fact, border_pix, low_rank_background, del_duplicates)
    266             print(len(args_in))
    267 
--> 268             file_res = dview.map_async(cnmf_patches, args_in).get(4294967)
    269         else:
    270             try:

~/anaconda/envs/caiman/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

ValueError: cannot reshape array of size 0 into shape (0)

- **If you're not reporting an error, type your message below**

**Comment by j-friedrich** [comment] 2018-05-21 13:06
Duplicate of already addressed issue #244.
Please do a fresh pull to update CaImAn.

**Closed by j-friedrich** 2018-05-21 13:06 UTC
