### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by clay34207** [flatironinstitute/CaImAn#986] opened 2022-06-15 14:06 UTC
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): macOS M1
 
 2. Python version (3.x): 3.10.5
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Python IDE
 
 4. Which of the demo scripts you're using for your analysis (if applicable): demo_pipeline.py
 
 5. CaImAn version*: 1.9.11
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): conda. Installed using both dev/non-dev in two different conda environments but still having the issue

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

In demo_pipeline.py, I get an index out of bounds error when trying to analyze one of my .tif files (generated from a z-projection of a 4D .nd2 file, not sure if that makes a difference). Also, when I try to use my file in the notebook version of this demo, the kernel dies after I execute mc.motion_correct(save_movie=True) in block 9.

- **Copy error log below**
/Users/claymallory/opt/anaconda3/envs/caiman2/lib/python3.10/site-packages/scipy/signal/_spectral_py.py:1961: UserWarning: nperseg = 256 is greater than input length  = 20, using nperseg = 20
  warnings.warn('nperseg = {0:d} is greater than input length '
/Users/claymallory/opt/anaconda3/envs/caiman2/lib/python3.10/site-packages/scipy/signal/_spectral_py.py:1961: UserWarning: nperseg = 256 is greater than input length  = 20, using nperseg = 20
  warnings.warn('nperseg = {0:d} is greater than input length '
/Users/claymallory/opt/anaconda3/envs/caiman2/lib/python3.10/site-packages/scipy/signal/_spectral_py.py:1961: UserWarning: nperseg = 256 is greater than input length  = 20, using nperseg = 20
  warnings.warn('nperseg = {0:d} is greater than input length '
/Users/claymallory/opt/anaconda3/envs/caiman2/lib/python3.10/site-packages/scipy/signal/_spectral_py.py:1961: UserWarning: nperseg = 256 is greater than input length  = 20, using nperseg = 20
  warnings.warn('nperseg = {0:d} is greater than input length '
/Users/claymallory/opt/anaconda3/envs/caiman2/lib/python3.10/site-packages/scipy/signal/_spectral_py.py:1961: UserWarning: nperseg = 256 is greater than input length  = 20, using nperseg = 20
  warnings.warn('nperseg = {0:d} is greater than input length '
/Users/claymallory/opt/anaconda3/envs/caiman2/lib/python3.10/site-packages/scipy/signal/_spectral_py.py:1961: UserWarning: nperseg = 256 is greater than input length  = 20, using nperseg = 20
  warnings.warn('nperseg = {0:d} is greater than input length '
/Users/claymallory/opt/anaconda3/envs/caiman2/lib/python3.10/site-packages/scipy/signal/_spectral_py.py:1961: UserWarning: nperseg = 256 is greater than input length  = 20, using nperseg = 20
  warnings.warn('nperseg = {0:d} is greater than input length '
/Users/claymallory/opt/anaconda3/envs/caiman2/lib/python3.10/site-packages/scipy/signal/_spectral_py.py:1961: UserWarning: nperseg = 256 is greater than input length  = 20, using nperseg = 20
  warnings.warn('nperseg = {0:d} is greater than input length '
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/claymallory/opt/anaconda3/envs/caiman2/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/claymallory/opt/anaconda3/envs/caiman2/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/claymallory/opt/anaconda3/envs/caiman2/lib/python3.10/site-packages/caiman/summary_images.py", line 784, in local_correlations_movie_parallel
    mv = cm.load(mv_name, subindices=idx, in_memory=True)
  File "/Users/claymallory/opt/anaconda3/envs/caiman2/lib/python3.10/site-packages/caiman/base/movies.py", line 1726, in load
    images = images[subindices]
  File "/Users/claymallory/opt/anaconda3/envs/caiman2/lib/python3.10/site-packages/numpy/core/memmap.py", line 334, in __getitem__
    res = super().__getitem__(index)
IndexError: index -980 is out of bounds for axis 0 with size 20
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/claymallory/caiman_data/demos/general/demo_pipeline.py", line 279, in <module>
    main()
  File "/Users/claymallory/caiman_data/demos/general/demo_pipeline.py", line 207, in main
    Cns = local_correlations_movie_offline(mc.mmap_file[0],
  File "/Users/claymallory/opt/anaconda3/envs/caiman2/lib/python3.10/site-packages/caiman/summary_images.py", line 773, in local_correlations_movie_offline
    parallel_result = dview.map_async(local_correlations_movie_parallel, params).get(4294967)
  File "/Users/claymallory/opt/anaconda3/envs/caiman2/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: index -980 is out of bounds for axis 0 with size 20

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment] 2022-06-15 14:33
Hello,
Can you share your notebook? I suspect the parameters you're using are the cause of this (I am leaving on a trip today - it may take me a little bit to look at the issue)

**Comment by clay34207** [comment] 2022-06-15 14:44
Thanks! Git won't let me upload it for some reason, but I'm using the demo_pipeline notebook file/.py file and the only thing I've changed locally is the file path so it looks at my file and not the default .tif it comes with.

**Comment by pgunn** [comment] 2022-06-15 14:50
Oh, that's surprising. I'd expect that error to come from changing some of the other parameters.

If you can find the smallest dataset that shows the problem, toss it onto dropbox, and then drop me an email with a link (please don't attach it to the ticket because the ticket is public), I can see what leads to it.

Please email pgunn@flatironinstitute.org (CC jfriedrich@flatironinstitute.org ) with a dropbox link (or if you prefer some other file sharing service that would work too).

If you can't share your data, let me know and we'll find some other way to diagnose (might take us longer)

**Comment by clay34207** [comment] 2022-06-15 15:04
Sure, I'm using a .tif file that's ~20 frames and 41 MB so it's not huge

**Comment by j-friedrich** [comment] 2022-06-15 16:05
20 frames is extremely short, usual data has 1000s. The `window` in `local_correlations_movie_offline` should be <= number of frames, and `winSize_baseline<=window/2` thus change these values accordingly.

**Comment by clay34207** [comment] 2022-06-15 17:25
@j-friedrich that fixed it for me, thanks. On an unrelated note, I encountered UnboundLocalError: local variable 'i' referenced before assignment. Looks like an indentation bug on line 2185 of movies.py, and it resolved when I indented that if block so it's within the scope of the for loop on line 2182.

**Comment by pgunn** [comment] 2022-06-22 16:00
@clay34207 I fixed that issue in rolling_window() ; I suspect your fix was not quite the right thing - you may want to undo it locally and try the fix in the diff below.

See:
5b203c269778eba6c7c2267bec9e317ea936cb1c

**Comment by EricThomson** [comment] 2023-05-01 18:25
Closing as it seems this has been addressed in a PR. Please reopen if this was a mistake @clay34207

**Closed by EricThomson** 2023-05-01 18:25 UTC
