### ISSUE TITLE
_cntr method does not exist in matplotlib 2.2.0

### ISSUE THREAD

**Issue by dougollerenshaw** [flatironinstitute/CaImAn#184] opened 2018-03-14 00:12 UTC
I just installed CaImAn in Windows 10 using the "environment_mac.yml". Matplotlib 2.2.0 was installed. Working through the 'demo_pipeline.ipynb' file in Jupyter, I ran into the following:

![mpl _cntr](https://user-images.githubusercontent.com/19944442/37376480-ad41c928-26e1-11e8-8bc6-f1250195614a.PNG)

Solved this by reverting to matplotlib 2.0.2 (conda install matplotlib=2.0.2). Should the specific version be specified in the environment file to help others avoid this?

**Comment by epnev** [comment] 2018-03-14 15:10
@j-friedrich This seems to be used only when plotting the contours in bokeh. Can you look into updating the code to be compatible? It seems to be a known issues:
https://stackoverflow.com/questions/18304722/python-find-contour-lines-from-matplotlib-pyplot-contour
and a possible solution:
http://scikit-image.org/docs/dev/auto_examples/edges/plot_contours.html

**Comment by j-friedrich** [comment] 2018-03-14 15:57
Duplicate of issue #174

**Closed by j-friedrich** 2018-03-14 15:57 UTC
