### ISSUE TITLE
dimensional ordering in get_contours() 

### ISSUE THREAD

**Issue by MaximilianHoffmann** [flatironinstitute/CaImAn#419] opened 2018-12-12 20:22 UTC
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**

https://github.com/flatironinstitute/CaImAn/blob/master/caiman/utils/visualization.py#L248

Says the dims are [x y z], which is compatible with the actual 3d output of the cnmf fit , but then

https://github.com/flatironinstitute/CaImAn/blob/master/caiman/utils/visualization.py#L277

this means, that the contour list /dict is returned in a x-list of YZ coordinates, since the ROIS are typically more sparse in XY and the number of z plane typically is smaller, I am not sure, why this solution is chosen. Also it seems to lead to errors in plot_contours, which I cannot properly trace back until now, so I leave this unspecified

**Comment by MaximilianHoffmann** [comment] 2018-12-12 20:55
Ok, so the grid initialised there, actually aren't use. But the problem persists.
I get it, it's good to loop over the first axis in
https://github.com/flatironinstitute/CaImAn/blob/master/caiman/utils/visualization.py#L312
 , but I wonder whether swapAxes should be set to true in the 3d case or something.

**Comment by epnev** [comment] 2019-01-07 16:55
@MaximilianHoffman I'm not sure I understand what the problem is. The code is complicated but it works fine. I'm closing this but feel free to reopen and provide more details.

**Closed by epnev** 2019-01-07 16:55 UTC
