### ISSUE TITLE
None of the backends could be imported

### ISSUE THREAD

**Issue by zyazdani-92** [flatironinstitute/CaImAn#1120] opened 2023-06-26 16:12 UTC
My setup:
 1. Operating System: MacOS M1
 2. Hardware type (x86, ARM..) and RAM: ARM64 - 8 GB
 3. Python Version: 3.10.10
 4. Caiman version: 1.9.15
 5. Which demo exhibits the problem: demo_pipeline_cnmfE
 6. How you installed Caiman: Conda distribution: Anoconda3 intel -  mamba package into my base environment: Mambaforge-MacOSX-x86_64 - CaImAn:  pip install .
 7. Details: 

I used `demo_dendritic` and `demo_pipeline_cnmfE`, after running the first cell, I encountered the following error,
I had no problem when I run `demo_pipeline`.
 
 `---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 32
     30 import holoviews as hv
     31 bpl.output_notebook()
---> 32 hv.notebook_extension('bokeh')

File ~/mambaforge/envs/caiman/lib/python3.10/site-packages/pyviz_comms/__init__.py:64, in extension.__new__(cls, *args, **kwargs)
     62 except Exception:
     63     pass
---> 64 return param.ParameterizedFunction.__new__(cls, *args, **kwargs)

File ~/mambaforge/envs/caiman/lib/python3.10/site-packages/param/parameterized.py:3658, in ParameterizedFunction.__new__(class_, *args, **params)
   3656 inst = class_.instance()
   3657 inst.param._set_name(class_.__name__)
-> 3658 return inst.__call__(*args,**params)

File ~/mambaforge/envs/caiman/lib/python3.10/site-packages/holoviews/ipython/__init__.py:116, in notebook_extension.__call__(self, *args, **params)
    114 def __call__(self, *args, **params):
    115     comms = params.pop('comms', None)
--> 116     super().__call__(*args, **params)
    117     # Abort if IPython not found
    118     try:

File ~/mambaforge/envs/caiman/lib/python3.10/site-packages/holoviews/util/__init__.py:718, in extension.__call__(self, *args, **params)
    713             self.param.warning('%s backend hook %s failed with '
    714                                'following exception: %s' %
    715                                (backend, hook, e))
    717 if selected_backend is None:
--> 718     raise ImportError('None of the backends could be imported')
    719 Store.set_current_backend(selected_backend)

ImportError: None of the backends could be imported`

**Comment by pgunn** [comment] 2023-06-26 17:05
Hello,
You're going to have a very rough time using caiman with only 8 gigabytes of RAM, but apart from that, can you clarify how you installed it? Between:

A) Grabbed the sources, and did mamba env create -n caiman -f environment.yml and then pip install .

and

B) mamba create -n caiman -c conda-forge caiman

Which did you do? You only need to do either A or B, not both. Route B is a much easier route.

Please let me know, although note again that this is a very underpowered system and you will likely have problems using caiman without having at least 16G (and ideally 32G) of RAM.

**Comment by zyazdani-92** [comment] 2023-06-26 17:21
Thanks for your answer. I used Method A!
However, in the past, I have used CaImAn multiple times with my current system. Despite my system not being optimal and taking a long time to produce results when using CaImAn, it still managed to perform its job.

**Comment by pgunn** [comment] 2023-06-26 18:35
Would you mind giving method B a go? You might have better luck with it.

**Comment by zyazdani-92** [comment] 2023-06-26 20:35
I reinstalled CaImAn using Method B! Unfortunately, I encountered the same error along with some warnings related to TensorFlow. I have copied all the warnings and errors below:

`/var/folders/0c/_vv7vm4n5z33nmfk83_ct2480000gn/T/ipykernel_23838/868823204.py:15: DeprecationWarning: `magic(...)` is deprecated since IPython 0.13 (warning added in 8.1), use run_line_magic(magic_name, parameter_s).
  get_ipython().magic('load_ext autoreload')
/var/folders/0c/_vv7vm4n5z33nmfk83_ct2480000gn/T/ipykernel_23838/868823204.py:16: DeprecationWarning: `magic(...)` is deprecated since IPython 0.13 (warning added in 8.1), use run_line_magic(magic_name, parameter_s).
  get_ipython().magic('autoreload 2')
2023-06-26 16:33:15.696663: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
 BokehJS 2.4.3 successfully loaded.
WARNING:param.notebook_extension: Holoviews bokeh extension could not be imported, it raised the following exception: ValueError('ClassSelector parameter None value must be an instance of (function, tuple), not <function size at 0x129bd0b70>.')
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 30
     28 import holoviews as hv
     29 bpl.output_notebook()
---> 30 hv.notebook_extension('bokeh')

File ~/mambaforge/envs/caiman/lib/python3.10/site-packages/pyviz_comms/__init__.py:64, in extension.__new__(cls, *args, **kwargs)
     62 except Exception:
     63     pass
---> 64 return param.ParameterizedFunction.__new__(cls, *args, **kwargs)

File ~/mambaforge/envs/caiman/lib/python3.10/site-packages/param/parameterized.py:3658, in ParameterizedFunction.__new__(class_, *args, **params)
   3656 inst = class_.instance()
   3657 inst.param._set_name(class_.__name__)
-> 3658 return inst.__call__(*args,**params)

File ~/mambaforge/envs/caiman/lib/python3.10/site-packages/holoviews/ipython/__init__.py:116, in notebook_extension.__call__(self, *args, **params)
    114 def __call__(self, *args, **params):
    115     comms = params.pop('comms', None)
--> 116     super().__call__(*args, **params)
    117     # Abort if IPython not found
    118     try:

File ~/mambaforge/envs/caiman/lib/python3.10/site-packages/holoviews/util/__init__.py:718, in extension.__call__(self, *args, **params)
    713             self.param.warning('%s backend hook %s failed with '
    714                                'following exception: %s' %
    715                                (backend, hook, e))
    717 if selected_backend is None:
--> 718     raise ImportError('None of the backends could be imported')
    719 Store.set_current_backend(selected_backend)

ImportError: None of the backends could be imported`

**Comment by pgunn** [comment] 2023-06-26 23:10
I wonder if this came from starting with mambaforge rather than miniconda (I generally recommend starting with miniconda, but some people have unfortunately been offering variant advice). One thing you might try is entirely uninstalling conda and installing miniconda instead and then reinstalling caiman (using route B) and see if that helps. But that's a lot of work. It still might do the job though.

In the meantime, it might be helpful to get a list of packages in your environment ; can you do a `conda list` and send the output into pastebin, and send me a link to that? Being able to look over that will help me a lot in terms of seeing what's going wrong.

And if you have time, consider the miniconda-instead-of-mambaforge route. It really might fix everything.

**Comment by BrainofZedZed** [comment] 2023-06-27 21:52
Wanted to pop in and add that I'm encountering the exact same bug. `demo_pipeline` loads but I'm replicating the error on `demo_pipeline_cnmfE`. Only difference in setup is I'm on Windows 11, 64 GB RAM, and used `mamba `instead of `pip` or `conda` to install.

[Here's a pastebin of the installed packages](https://pastebin.com/QYgr9ARP).

I'm going to tinker and see if I can solve it. If I can't, I'll try using miniconda instead of mambaforge.

**Comment by pgunn** [comment] 2023-06-27 23:19
I'm giving it a go too - made another account on my home workstation (Linux), installing mambaforge on it, and using mamba to do a caiman install; will see if that gives me an environment that manifests the problem. If so, this will give me a relatively nondestructive basis to investigate. If not, I'll have to weigh destroying one of my development environments to dig into this.

**Comment by pgunn** [comment] 2023-06-27 23:23
Ok, reproduced on my system with mambaforge.

**Comment by pgunn** [comment] 2023-06-27 23:36
And unfortunately, reproduced on my system with non-mambaforge conda as well. I think something must have broken upstream that's not related to mambaforge. This needs some more investigation.

**Comment by pgunn** [comment] 2023-06-28 01:32
Fixed in dev (probably), but will also need adjustment to the feedstock (and will take a new release to really be fixed).

**Comment by BrainofZedZed** [comment] 2023-06-28 14:43
Awesome. Thanks for resolving that, Pat!

**Comment by melkalliny** [comment] 2023-07-04 00:50
I second the thanks, that resolved a similar issue for me.

FYI though, that may have turned up an issue down the line. When trying to inspect the CNMF initialization using cnm.estimates.plot_contours_nb(img=Cn), it sent me to the exception on line 309 of estimates.py due to 'crd' being undefined. I think that exception was triggered by 'plot_width' and 'plot_height' no longer being part of the naming for the latest version of bokeh, so I changed the naming inside estimates.py and visualization.py to 'width' and 'height'. That seems to get me past the error and to plot the contours. 
(I'm not seeing the correlation image underneath but that may be a separate issue, haven't looked into it yet)

**Comment by pgunn** [comment] 2023-07-04 01:22
Thanks for letting us know - looks like this is another thing to look into (both the bokeh changing and the correlation image issue). Seems every dependency is another rug that can be pulled out from under our too-many-feet. I'll file another bug to track that, and close this issue.

**Closed by pgunn** 2023-07-04 01:22 UTC
Labels: type: bug
