### ISSUE TITLE
Update/Installation issue - FileNotFoundError: [WinError 3] The system cannot find the path specified: 'bin'

### ISSUE THREAD

**Issue by donglabimaging** [flatironinstitute/CaImAn#756] opened 2020-05-22 21:30 UTC
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
Win 10 
 
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Anaconda

 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
pip install -e .

- **Describe the issue that you are experiencing**
We are attempting to update CaImAn from caiman 1.0 by following the documentation on https://caiman.readthedocs.io/en/master/Installation.html. Below are the steps we did:

1) `pip uninstall caiman`
2) `conda env remove -n caiman`
3) Close and reopen your shell (to clear out the old conda environment)
4) Instead of doing `git pull`, i renamed the Caiman folder to Caiman_backup and did git clone https://github.com/flatironinstitute/CaImAn
5) `cd CaImAn`
6) `conda env create -f environment.yml -n caiman`
7) `conda install -n caiman vs2017_win-64`
8) Deleted the VS startup script vs2017_compiler_vars.bat
9) `conda activate caiman`
10) `pip install -e .`
11) `copy caimanmanager.py ..`
12) `cd ..`
13) `python caimanmanager.py install --inplace`

The following error shows up after line 13.  Any suggestions would be greatly appreciated.  Thank you!

- **Copy error log below**
(caiman) C:\Users\allenli>python C:\Users\allenli\caimanmanager.py install --inplace
C:\Users\allenli\Anaconda3\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\allenli\Anaconda3\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\allenli\Anaconda3\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\allenli\Anaconda3\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\allenli\Anaconda3\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\allenli\Anaconda3\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "C:\Users\allenli\caimanmanager.py", line 272, in <module>
    main()
  File "C:\Users\allenli\caimanmanager.py", line 230, in main
    do_install_to(cfg.userdir, cfg.inplace, cfg.force)
  File "C:\Users\allenli\caimanmanager.py", line 66, in do_install_to
    shutil.copytree(copydir, os.path.join(targdir, copydir))
  File "C:\Users\allenli\Anaconda3\envs\caiman\lib\shutil.py", line 318, in copytree
    names = os.listdir(src)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'bin'

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment] 2020-05-22 22:54
Hi,
Before we dig in, do you intend to modify the caiman sourcecode? If you don't need that, there's an easier way to manage the install without pip.

**Comment by donglabimaging** [comment] 2020-05-25 22:46
Hi @pgunn, 

Thank you for the reply.  I'm glad to hear that there is a easy way to fix this.  We do not intend to modify the caiman sourcecode.  

Thanks,

Allen

**Comment by pgunn** [comment] 2020-05-25 23:20
I suggest removing your checkout of the caiman sources, then doing

`conda install -c conda-forge caiman`

This will use our already-packaged version of caiman, which we think you will have more luck with (you will still want to do a `caimanmanager.py install` )

**Comment by donglabimaging** [comment] 2020-05-25 23:21
I will try that right now.  Thank you!

**Comment by donglabimaging** [comment] 2020-05-26 00:12
I ran `caimanmanager.py install` and received the following error.
ModuleNotFoundError: No module named 'caiman'

I did the following prior to receiving the error:
1. `pip uninstall caiman`
2. `conda env remove -n caiman`
3. `Closed and opened the shell`
4. `conda create -n caiman`
5. `conda activate caiman`
6. `conda install caiman -c conda-forge`

**Comment by donglabimaging** [comment] 2020-05-26 00:25
Using `python caimanmanager.py install` worked!
Installed C:\Users\username\caiman_data

**Comment by epnev** [comment] 2020-05-27 22:42
From what I understand the issue is resolved. Closing

**Closed by epnev** 2020-05-27 22:42 UTC

**Comment by donglabimaging** [comment] 2020-05-28 03:23
@pgunn @epnev  
Thank you guys for all the help.
