### ISSUE TITLE
Problem with running the 3D demo notebook

### ISSUE THREAD

**Issue by PaulinaWysmolek** [flatironinstitute/CaImAn#745] opened 2020-04-28 14:23 UTC
1. Operating system (Linux/macOS/Windows): 
 macOS High Sierra (10.13.6)
 2. Python version (3.x): 
 3.6.10
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Jupyter Notebook (opened via Anaconda Navigator)

 4. Which of the demo scripts you're using for your analysis (if applicable):
 Volumetric data processing [3D notebook](https://github.com/flatironinstitute/CaImAn/blob/master/demos/notebooks/demo_caiman_cnmf_3D.ipynb)
 5. CaImAn version*: 
 1.8.2 (according to the file VERSION in the caiman_data folder)
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
For installation I used 
```
git clone https://github.com/flatironinstitute/CaImAn
cd CaImAn/
conda env create -f environment.yml -n caiman
source activate caiman
pip install -e
```

Hello,
I am very interested in your noteboook for volumetric data processing as I have a lot of 1p xyzt stacks to analyse. I tried running your demo notebook ( 3D demo notebook, with the demo data not mine ). The script can save and then load a memory mapped file and show a max-projection of the correlation image

![corr im](https://user-images.githubusercontent.com/64419168/80497980-783d2300-896b-11ea-8ea4-430d9bb53a82.jpg)

(it seems reasonable I think...?)
but as soon as 
1. `cnm.estimates.nb_view_components_3d(image_type='mean', dims=dims) ;`
or
2. `cnm2.estimates.nb_view_components_3d(image_type='corr', dims=dims, Yr=Yr, denoised_color='red', max_projection=True);`

were called I got an error message:

`AttributeError: unexpected attribute 'callback' to Slider, similar attributes are js_event_callbacks`

Just in case, I am also attaching screens shot of the error message showing up for both 1. and 2.

I was not able to pinpoint the problem - I would therefore be very grateful for your help...

Many many thanks and best regards,
Paulina

![occurence of failure](https://user-images.githubusercontent.com/64419168/80496267-4034e080-8969-11ea-9f4a-e9c57fb16b70.jpg)
![occurance of failure2](https://user-images.githubusercontent.com/64419168/80497379-a79f6000-896a-11ea-8922-52ba53800e37.jpg)

**Comment by j-friedrich** [comment] 2020-04-28 15:12
Duplicate of already solved #732.

You need to do a `git pull` and [upgrade](https://github.com/flatironinstitute/CaImAn/blob/master/docs/source/Installation.rst#upgrading-and-source-based-installations) to caiman 1.8.3 which supports bokeh2.

Closing the issue, but feel free to reopen if you have trouble upgrading

**Closed by j-friedrich** 2020-04-28 15:12 UTC
