### ISSUE TITLE
detrend_df_f 

### ISSUE THREAD

**Issue by tbenst** [flatironinstitute/CaImAn#429] opened 2019-01-09 06:45 UTC
- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**

Linux Jupyter

- **Describe the issue that you are experiencing**

After `cnm2.estimates.evaluate_components` suceeds in demo_pipeline, on about 50% of my zplanes, `cnm2.estimates.detrend_df_f(quantileMin=8, frames_window=250)` fails deterministically. The other 50% of my zplanes succeed with no problem, suggesting a possible numerical problem.

- **Copy error log below**

Please see https://gist.github.com/tbenst/cebc3ed130a53b458fca7cc043b4f9f8

Thanks so much for all the help!!

**Comment by epnev** [comment] 2019-01-09 14:20
@tbenst In one of the planes where this fails can you check whether there are NaN values in `estimates.A, estimates.C, estimates.b, estimates.f`?

**Comment by tbenst** [comment] 2019-01-09 17:06
@epnev I can confirm that there are no NaN values in any of those 4.

**Comment by epnev** [comment] 2019-01-10 19:32
@tbenst I've never encountered this error before and it occurs on a function I didn't implement so I'm a bit confused. Can you try running `cnm2.estimates.detrend_df_f` but also setting the optional argument `flag_auto=False`?

**Comment by tbenst** [comment] 2019-01-10 20:41
@epnev I will try but may take me a few days before I can run CaImAn again. FYI, these same planes run fine on an older version of CaImAn that someone else in lab had installed, but not on the latest. Were you able to reproduce the error in the code I posted?

**Comment by epnev** [comment] 2019-01-10 20:45
@tbenst Thanks. Yes, I was able to reproduce and pretty much suggested to roll back to the previous version of this function, until I figure out how to fix this. Will take a closer look.

**Comment by tbenst** [comment] 2019-01-10 20:47
oh great, thank you!

**Comment by epnev** [comment] 2019-01-11 16:11
@tbenst The `kde` function fails in a way that I don't understand. However I believe that it has to do with the vector being somewhat short. I introduced a workaround in the detrending function that doubles the length of the vector by appending a copy if the kde function fails (the estimate will be the same since the histogram does not change by introducing a copy of the data). https://github.com/flatironinstitute/CaImAn/commit/ef7a25956d94871e3bfc061c7915abfde9879b5d
so the short script you copied will still fail but the `df_percentile` function that calls it will not. I believe it should work now but let me know when you get a chance.

**Comment by epnev** [comment] 2019-02-13 17:50
@tbenst I'm closing the issue but feel free to re-open if you're still encountering problems. The fix has been pushed to the master branch.

**Closed by epnev** 2019-02-13 17:50 UTC
