### ISSUE TITLE
Running out of Memory and Motion Correction patches moving separately. 

### ISSUE THREAD

**Issue by JLRomero12** [flatironinstitute/CaImAn#1079] opened 2023-05-11 15:41 UTC
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): Windows 10
 2. Hardware type (x86, ARM..) and RAM: AMD Ryzen Threadripper 2950X 16-Core Processor 3.50 GHz, 256GB RAM
 3. Python Version (e.g. 3.9): Python 3.10
 4. Caiman version (e.g. 1.9.12): Caiman 1.9.15
 5. Which demo exhibits the problem (if applicable): dem_pipeline_cnmfe.py
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): I installed Caiman through Mescore (mamba create -n mescore -c conda-forge mesmerize-core) though I am not using any of the mesmerize scripts and just using regular caiman. 
 7. Details: 

I am having two problems:
1- I am currently working with 500x500 pixels 1 hour long 1p recordings. I can do motion correction without running out of memory by using the right n_processes value. When I get to the CNMF portion, I am having trouble creating a Correlation and PNR images using summary_images.correlation_pnr. I run out of memory (it says it cannot allocate around 64 GB). However, it seems like the problem is while it is trying to concatenate two numpy arrays (I can replicate the error if needed). Is there any way to create this image so my computer will not run out of memory? It runs the CNMFE totally ok if I just skip creating the image, but it is very nice for visualization purposes. 

2 - My biggest problem so far. In my hour-long motion correction video, some lines are created as a result of the patches of the motion correction. This is true in both 'pw-rigid = True' and 'pw-rigid = False' videos (which I thought if doing rigid it didn't use the patches but maybe I am mistaken). This is what it looks like in the estimates.view_components plot:

![image](https://github.com/flatironinstitute/CaImAn/assets/32527055/daed0afc-a4c4-4945-a896-6c98b3ce461d)

The motion correction was created using the following parameters:
   pw_rigid            = False                     # flag for performing rigid or piecewise rigid motion correction
   gSig_filt           = (int(12 * ds),int(12 * ds))   # size of filter, in general gSig (see below),
   strides             = (int(64 * ds),int(64 * ds))   # create a new patch every x pixels for pw-rigid correction
   overlaps            = (int(32 * ds),int(32 * ds))   # overlap between pathes (size of patch strides+overlaps)
   max_shifts          = (int(12 * ds),int(12 * ds))   # maximum allowed rigid shift in pixels (view the movie to get a sense of motion)
   max_deviation_rigid =  int(12 * ds)       # maximum deviation allowed for patch with respect to rigid shifts
   shifts_opencv       = True      # flag for correcting motion using bicubic interpolation (otherwise FFT interpolation is used)
   border_nan          = 'copy'    # replicate values along the boundary (if True, fill in with NaN)

I also have tried doing a rigid pass and then a piecewise pass in the motion correction, and though I get much better results in the stabilization of the video, I still see those ugly lines in the view_components plots. Looking at the motion corrected videos, I can see the patches moving separately. Am I just using the wrong parameters?? I would greatly appreciate some advice on this.

**Comment by EricThomson** [comment] 2023-05-11 16:22
For the first problem with `corr_pnr` calculation, you can subsample as described in the notebook

>  You can do that by changing images[::1] to images[::5] or something similar

I'm much more concerned with the block artifacts. What is `ds`?  What is its value?

Note `gsig_filt` is in general not the same as `gsig`: the former is for high pass filtering the movie before applying motion correction of the 1p data. The latter is for finding neurons during CNMFE and is the radius of the neuron in pixels (roughly).  So if you have large-diameter neurons you will end up with gsig >> gsig_filt.

**Comment by JLRomero12** [comment] 2023-05-11 16:50
Thank you so much for the help Eric. `ds` is just what we used for downsampling the videos while we were testing different parameters. We load the videos like this:

    ds = 1          # frame downsampling, 1 for no downsampling, 0.5 for half-sized frames
    decay_time = 0.4  #length of a typical transient in seconds

    longClip=True
    if longClip:
        fnames = ['0.avi','1.avi','2.avi','3.avi','4.avi'] #This goes up to 59.avi for the full one hour recording.
        saveprefix='0-59'
    else:
        fnames = ['0.avi']
        saveprefix='0'

    m_orig = cm.load(fnames)      # a numpy array of all the frames T,Y,X
    
    # downsample
    m_orig = m_orig.resize(ds,ds,1)`

Then we make the motion correction object using m_orig.

    pw_rigid            = False                     # flag for performing rigid or piecewise rigid motion correction
    gSig_filt           = (int(12*ds),int(12*ds))   # size of filter, in general gSig (see below),
    strides             = (int(64*ds),int(64*ds))   # create a new patch every x pixels for pw-rigid correction
    overlaps            = (int(32*ds),int(32*ds))   # overlap between pathes (size of patch strides+overlaps)
    max_shifts          = (int(12*ds),int(12*ds))   # maximum allowed rigid shift in pixels (view the movie to get a sense of motion)
    max_deviation_rigid =  int(12*ds)       # maximum deviation allowed for patch with respect to rigid shifts
    shifts_opencv       = True      # flag for correcting motion using bicubic interpolation (otherwise FFT interpolation is used)
    border_nan          = 'copy'    # replicate values along the boundary (if True, fill in with NaN) `
    
    mc_dict = {
        'fnames': fnames,
        'fr': fps,
        'decay_time': decay_time,
        'pw_rigid': pw_rigid,
        'max_shifts': max_shifts,
        'gSig_filt': gSig_filt,
        'strides': strides,
        'overlaps': overlaps,
        'max_deviation_rigid': max_deviation_rigid,
        'border_nan': border_nan
    }

    opts = params.CNMFParams(params_dict=mc_dict)
    
    # create a motion correction object
    mc = MotionCorrect(m_orig, dview=dview, max_shifts=max_shifts,
                      strides=strides, overlaps=overlaps,
                      max_deviation_rigid=max_deviation_rigid, 
                      shifts_opencv=shifts_opencv, nonneg_movie=True,
                      border_nan=border_nan,gSig_filt=gSig_filt,pw_rigid=pw_rigid)'


Thank you so much for the advice on the corr_pnr calculation, I'll implement it and let you know. Also thank you for the note

**Comment by EricThomson** [comment] 2023-05-11 17:39
Great thanks for the clarification. My first thought is 12 is pretty big for `gsig_filt` and might yield some weirdness. Have you tried making it smaller like 5?

By the way, I like this way of handling propagating downsampling through your parameters!

**Comment by JLRomero12** [comment] 2023-05-11 19:07
Hi Eric, 

Thank you again for taking the time to help me. I changed my `gsig_filt` to 5 and still got the artifacts.

![image](https://github.com/flatironinstitute/CaImAn/assets/32527055/ac6521a0-96c5-43cd-9169-3b6e0f3183f2)

You can see in this picture how the ROI gets cut off on the right and bottom. That happens for almost all of my videos. Do you know what other parameter I can change?? Also, the motion correction for this CNMFE was done with a rigid pass first, and then a piecewise pass on the "rigid motioned corrected" memmap. Is there anything else I can show you to give you a better idea of what could be happening? Also, these videos are encoded in the GREY when originally recorded as opposed to FFV1, but it seems to be loading ok into caiman despite the weird encoding. 

Thanks for the compliment! I wish I could take credit for it but those changes were done by my colleague. I will pass it down to him though!

**Comment by EricThomson** [comment] 2023-05-11 19:16
Hmm, this is truly strange I'm not sure what to make of it. If you are ok sharing data, do you mind sharing a short (i.e., 1000 to 2000 frame) sample of your original video to see if we can reproduce this problem? Either on Dropbox, Google Drive, or something?

**Comment by JLRomero12** [comment] 2023-05-11 19:49
Would you like the video before motion correction or after?

**Comment by EricThomson** [comment] 2023-05-11 20:01
Before as I'd like to try to reproduce the artifact.

**Comment by JLRomero12** [comment] 2023-05-11 20:30
Makes sense! Please try this link, it is 2400 frames (the video is at 60 fps but the framerate is actually 20 fps). I ran it through my pipeline and did get the artifacts though not as prominent as longer videos 

https://ucla.box.com/s/ft2wjd850hk7xti0clo2xnb6w8z2cr75

Let me know if there are issues downloading! Thank you again!

**Comment by EricThomson** [comment] 2023-05-11 20:46
Thanks. It may take me a while to get to it, like next week sometime is my guess.

**Comment by JLRomero12** [comment] 2023-05-11 22:47
Thank you so much Eric! Please take your time! I am excited to see what you find.

**Comment by kushalkolar** [comment] 2023-05-12 02:33
The mesmerize-core demo nb for cnmfe has a visualization that can help you find a good gSig_filt, and optimize your other params with gridsearch: https://github.com/nel-lab/mesmerize-core/blob/master/notebooks/cnmfe.ipynb

https://user-images.githubusercontent.com/9403332/231554268-2f0fa7f3-0286-4195-b316-bcdea5921771.mp4

**Comment by EricThomson** [comment] 2023-05-12 13:20
I would recommend mesmerize-core for this. Basically, what I would do with 1p motion correctoin problems:
1. Pick the 1000 frames or so in the vicinity of the worst motion problems in the full video and work on that, don't waste time doing motion correction on the full video because it takes a really long time (you can do this with indexing you don't have to literally subset the video).
2. Crop the video in space too: are there neurons everywhere in the video? Probably not. Especially if there are regions in the video where there are expanses with no features, that will really mess up motion correction, because it works with cross-correlation. If there are no featuers, then xcorr will go haywire and get messed up. Plus, spatially cropped vids mean much faster analysis. Again, you can do this with indexing, or just crop before you do anything else and generate a cropped tiff (or avi which is what you have). 
3. Then, and only then, when I have a recalcitrant data set, will I really start exploring parameter space otherwise I spend too much time on it. The main params that make a big difference for 1p are `gsig_filt` and `max_shifts`. `gsig_filt` vals are usually small, like between 2-5. `max_shifts` are usually big, like 20+ (it depends on your movie obviously, but there are some big jumps in your movie -- I usually pick twice what I think the max pixel movement is). Also to really make sure the `pw_rigid` is off, make sure `rf` is `None` (that shouldn't make a difference, but just try it :) ).  There is also a motion correction param that isn't documented in the CNMFE notebook `niter_rig`, the number of iterations of rigid motion correction: it will run through it that many times iteratively. So maybe set that to 3 or something to see if it helps.

So I would play around with that, see if you still get artifacts. You shouldn't, but if you do I'd be very curious. This is what I would do if I played with your data.

You will still likely have some residual movement after running rigid motion. If not, you can stop there. If you do, then besure when you run pw_rigid, I would set `max_deviation_rigid` *way* smaller than 12, like usually around 3 pixels or so, otherwise I wouldn't be surprised if you got some weird tearing artifacts like you are seeing.

@kushalkolar's library has some great ways to explore this stuff.

**Comment by JLRomero12** [comment] 2023-05-17 19:57
Hello Eric and Kushal, 

Thank you so much for the help. We were able to figure out what the problem was! It wasn't an issue with the motion correction but instead an issue with the patches in the CNMF. We set `rf = None` and `stride = None,` and the problem is mainly solved. However, there are still issues in the motion correction where the patches move separately, so we are still trying to fine-tune the parameters. Thank you so much for your help!

**Comment by kushalkolar** [comment] 2023-05-17 20:17
I think there's a params like `upsample_grid` which i used to use a few years ago to prevent tearing, I'm not sure if it has an effect anymore but you could try that.

**Comment by EricThomson** [comment] 2023-05-18 00:09
@JLRomero12 that's great: there are also tricks for piecewise rigid, like what Kushal mentioned, and increasing overlap. Basically params are super important. :)

**Comment by EricThomson** [comment] 2023-05-18 15:21
I'm closing this issue for now, but I think we need to do a better job explaining the types of problems that can arise, and what parameters can fix them, when the standard parameters don't work, for motion correction, and cnmf.

Please feel free to open another issue or chat with us in gitter if another problem arises in different stages.

**Closed by EricThomson** 2023-05-18 15:21 UTC
Labels: type: question
