### ISSUE TITLE
error in isolated call of tile_and_correct_3d

### ISSUE THREAD

**Issue by MaximilianHoffmann** [flatironinstitute/CaImAn#751] opened 2020-05-08 10:17 UTC
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
Linux
 
 2. Python version (3.x): 
3.6
 
 3. Working environment (Python IDE/Jupyter Notebook/other):
 jupyter notebook
 4. Which of the demo scripts you're using for your analysis (if applicable):
 -
 5. CaImAn version*: 
 just pulled from master.

 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
none

- **Describe the issue that you are experiencing**

I wanted to test the motion correction without employing the whole pipeline.
(I copied all the used functions into an isolated normcorre.py file)

When calling

```
print(vol1_c.shape)
print(vol1_c.dtype)
print(tmpl.shape)
print(tmpl.dtype)
normcorre.tile_and_correct_3d(vol1_c,tmpl,[50,50,50],[10,10,10],[5,5,5])
```
I get
```
(125, 750, 200)
float32
(125, 750, 200)
float32

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-157-5a02ec24403a> in <module>
      3 print(tmpl.shape)
      4 print(tmpl.dtype)
----> 5 normcorre.tile_and_correct_3d(vol1_c,tmpl,[50,50,50],[10,10,10],[5,5,5])

 in tile_and_correct_3d(img, template, strides, overlaps, max_shifts, newoverlaps, newstrides, upsample_factor_grid, upsample_factor_fft, show_movie, max_deviation_rigid, add_to_movie, shifts_opencv, gSig_filt, use_cuda, border_nan)
    230 
    231             for (x, y, z), (idx_0, idx_1, idx_2), im, (_, _, _), weight_mat in zip(start_step, xyz_grid, imgs,
--> 232                                                                                    total_shifts, weight_matrix):
    233 
    234                 if idx_0 == 0:

 in create_weight_matrix_for_blending(img, overlaps, strides)
    778         if grid_1 < max_grid_1:
    779             weight_mat[-overlaps[0]:,
--> 780                        :] = np.linspace(1, 0, overlaps[0])[:, None]
    781         if grid_2 > 0:
    782             weight_mat[:, :overlaps[1]] = weight_mat[:, :overlaps[1]

ValueError: could not broadcast input array from shape (10,1) into shape (10,22,22)
```
Maybe I make an error that is easily correctable?

I would be grateful for any input.

**Comment by epnev** [comment] 2020-05-09 13:17
@MaximilianHoffmann It would be much easier to understand what the problem is if you run the original CaImAn code. I'll close this issue and you suggest you open a new one with the error log that the original codebase gives.

**Closed by epnev** 2020-05-09 13:17 UTC

**Comment by MaximilianHoffmann** [comment] 2020-05-09 17:55
I understand, I didn't want to install holoviews, because it breaks my interactive jupyterlab plotting even from a different environment, anyway. I pulled the new repository 20 min ago.
```
from caiman.motion_correction import tile_and_correct_3d
import numpy as np                                                      
a=np.random.rand(100,100,100)                                           
b=np.random.rand(100,100,100)                                           
 tile_and_correct_3d(a,b,[20,20,20],[5,5,5],[2,2,2])  
```
yields
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-59f40a3b606d> in <module>
      3 a=np.random.rand(100,100,100)
      4 b=np.random.rand(100,100,100)
----> 5 tile_and_correct_3d(a,b,[20,20,20],[5,5,5],[2,2,2]
      6 
      7 

/fast/work/users/hoffmmax_c/repos/CaImAn/caiman/motion_correction.py in tile_and_correct_3d(img, template, strides, overlaps, max_shifts, newoverlaps, newstrides, upsample_factor_grid, upsample_factor_fft, show_movie, max_deviation_rigid, add_to_movie, shifts_opencv, gSig_filt, use_cuda, border_nan)
   2457             half_overlap_z = np.int(newoverlaps[2] / 2)
   2458 
-> 2459             for (x, y, z), (idx_0, idx_1, idx_2), im, (_, _, _), weight_mat in zip(start_step, xyz_grid, imgs, total_shifts, weight_matrix):
   2460 
   2461                 if idx_0 == 0:

/fast/work/users/hoffmmax_c/repos/CaImAn/caiman/motion_correction.py in create_weight_matrix_for_blending(img, overlaps, strides)
   1976         if grid_1 < max_grid_1:
   1977             weight_mat[-overlaps[0]:,
-> 1978                        :] = np.linspace(1, 0, overlaps[0])[:, None]
   1979         if grid_2 > 0:
   1980             weight_mat[:, :overlaps[1]] = weight_mat[:, :overlaps[1]

ValueError: could not broadcast input array from shape (5,1) into shape (5,10,10)
```
