### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by SophiePinder** [flatironinstitute/CaImAn#851] opened 2021-02-01 17:50 UTC
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Linux
 
 2. Python version (3.x): 3.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other): jupyter notebook
 
 4. Which of the demo scripts you're using for your analysis (if applicable): demo_online_Cnmfe
 
 5. CaImAn version*: latest
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): conda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

When I change the min_pnr and min_cor values, I get the below error when i run the following code.
I've look at other issues but i can't seem to find the solution.
from time import time
t1 = -time()
cnm = cnmf.CNMF(n_processes=n_processes, dview=dview, params=opts)
cnm.fit(images)
t1 += time()

- **Copy error log below**

from time import time

t1 = -time()

cnm = cnmf.CNMF(n_processes=n_processes, dview=dview, params=opts)

cnm.fit(images)

t1 += time()

---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/s/scp27/miniconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/s/scp27/miniconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/s/scp27/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/map_reduce.py", line 137, in cnmf_patches
    cnm = cnm.fit(images)
  File "/home/s/scp27/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 506, in fit
    self.initialize(Y)
  File "/home/s/scp27/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 966, in initialize
    **self.params.get_group('init'))
  File "/home/s/scp27/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/initialization.py", line 354, in initialize_components
    sn=sn, nb=nb, ssub=ssub, ssub_B=ssub_B, init_iter=init_iter, seed_method=seed_method)
  File "/home/s/scp27/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/initialization.py", line 1304, in greedyROI_corr
    dview=None, dims=(d1, d2), **options['spatial_params'])
  File "/home/s/scp27/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/spatial.py", line 269, in update_spatial_components
    f = np.delete(f, background_ff, 0)
  File "<__array_function__ internals>", line 6, in delete
  File "/home/s/scp27/miniconda3/envs/caiman/lib/python3.7/site-packages/numpy/lib/function_base.py", line 4406, in delete
    keep[obj,] = False
IndexError: index 1 is out of bounds for axis 0 with size 0
"""

The above exception was the direct cause of the following exception:

IndexError                                Traceback (most recent call last)
<ipython-input-22-595bc5cd7ebe> in <module>
      2 t1 = -time()
      3 cnm = cnmf.CNMF(n_processes=n_processes, dview=dview, params=opts)
----> 4 cnm.fit(images)
      5 t1 += time()

~/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/cnmf.py in fit(self, images, indices)
    604                     low_rank_background=self.params.get('patch', 'low_rank_background'),
    605                     del_duplicates=self.params.get('patch', 'del_duplicates'),
--> 606                     indices=indices)
    607 
    608             self.estimates.bl, self.estimates.c1, self.estimates.g, self.estimates.neurons_sn = None, None, None, None

~/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/map_reduce.py in run_CNMF_patches(file_name, shape, params, gnb, dview, memory_fact, border_pix, low_rank_background, del_duplicates, indices)
    245     if dview is not None:
    246         if 'multiprocessing' in str(type(dview)):
--> 247             file_res = dview.map_async(cnmf_patches, args_in).get(4294967)
    248         else:
    249             try:

~/miniconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

IndexError: index 1 is out of bounds for axis 0 with size 0

- **If you're not reporting an error, type your message below**

**Comment by j-friedrich** [comment] 2021-02-08 14:11
@SophiePinder For which values of `min_pnr` and `min_cor` do you get the error (leaving the rest of the notebook unchanged)?

**Comment by SophiePinder** [comment] 2021-02-09 09:48
min_pnr=6
min_cor=0.2

**Comment by j-friedrich** [comment] 2021-02-09 16:39
Duplicate of #808
Please make sure you use indeed the latest version of caiman.
I checked and it works just fine with `min_pnr=6` and `min_cor=0.2`

**Comment by SophiePinder** [comment] 2021-02-09 17:23
@j-friedrich I'm using my own data set not the demo data, could this be a reason for this error?

**Comment by j-friedrich** [comment] 2021-02-09 18:42
@SophiePinder can you insert the line `nr = C.shape[0]` before line 252 (`A_ = scipy.sparse.coo_matrix...`) in file `CaImAn/caiman/source_extraction/cnmf/spatial.py` and report back whether that solves the issue. 
It looks as if an empty or nan component has been removed earlier in the code, but `nr` has not been updated to the correct value.

**Comment by SophiePinder** [comment] 2021-02-09 19:46
@j-friedrich it didn't work, I got the same error

---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/s/scp27/miniconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/s/scp27/miniconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/s/scp27/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/map_reduce.py", line 137, in cnmf_patches
    cnm = cnm.fit(images)
  File "/home/s/scp27/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 506, in fit
    self.initialize(Y)
  File "/home/s/scp27/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 966, in initialize
    **self.params.get_group('init'))
  File "/home/s/scp27/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/initialization.py", line 354, in initialize_components
    sn=sn, nb=nb, ssub=ssub, ssub_B=ssub_B, init_iter=init_iter, seed_method=seed_method)
  File "/home/s/scp27/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/initialization.py", line 1304, in greedyROI_corr
    dview=None, dims=(d1, d2), **options['spatial_params'])
  File "/home/s/scp27/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/spatial.py", line 270, in update_spatial_components
    f = np.delete(f, background_ff, 0)
  File "<__array_function__ internals>", line 6, in delete
  File "/home/s/scp27/miniconda3/envs/caiman/lib/python3.7/site-packages/numpy/lib/function_base.py", line 4406, in delete
    keep[obj,] = False
IndexError: index 0 is out of bounds for axis 0 with size 0
"""

The above exception was the direct cause of the following exception:

IndexError                                Traceback (most recent call last)
<ipython-input-12-595bc5cd7ebe> in <module>
      2 t1 = -time()
      3 cnm = cnmf.CNMF(n_processes=n_processes, dview=dview, params=opts)
----> 4 cnm.fit(images)
      5 t1 += time()

~/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/cnmf.py in fit(self, images, indices)
    604                     low_rank_background=self.params.get('patch', 'low_rank_background'),
    605                     del_duplicates=self.params.get('patch', 'del_duplicates'),
--> 606                     indices=indices)
    607 
    608             self.estimates.bl, self.estimates.c1, self.estimates.g, self.estimates.neurons_sn = None, None, None, None

~/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/map_reduce.py in run_CNMF_patches(file_name, shape, params, gnb, dview, memory_fact, border_pix, low_rank_background, del_duplicates, indices)
    245     if dview is not None:
    246         if 'multiprocessing' in str(type(dview)):
--> 247             file_res = dview.map_async(cnmf_patches, args_in).get(4294967)
    248         else:
    249             try:

~/miniconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by j-friedrich** [comment] 2021-03-22 20:03
@SophiePinder did you ever figure out why for your data `nr` and `C.shape[0]` have apparently different values at line 259 of spatial.py? What values do they have? 
If you are using CNMF-E, you can set `update_background_components` to `False` (CNMF-E models the background differently and this parameter should have no effect), to avoid this error.

**Comment by hahnjohannes** [comment] 2021-04-16 13:04
@SophiePinder @j-friedrich Did you figure out a solution for this? I think I'm having the same/similar issue. It works well with the downloaded demo file but not with my data.  

I also tried setting  'update_background_components': False (in cnmfe_dict, is this right?) but this didn't help. 

I could also send you the file I'm trying to run, maybe there is an issue with that. 


- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Windows 10
 2. Python version (3.x):  
 3. 3.7.10
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Jupyter Notebook
 4. Which of the demo scripts you're using for your analysis (if applicable):
 demo_online_cnmfE.ipynb (with custom miniscope avi file)
 5. CaImAn version*: 
 1.8.8
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda

- **Describe the issue that you are experiencing**
as above


- **Copy error log below**

---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\USER\.conda\envs\caiman\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\USER\.conda\envs\caiman\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\USER\.conda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\map_reduce.py", line 137, in cnmf_patches
    cnm = cnm.fit(images)
  File "C:\Users\USER\.conda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py", line 506, in fit
    self.initialize(Y)
  File "C:\Users\USER\.conda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py", line 966, in initialize
    **self.params.get_group('init'))
  File "C:\Users\USER\.conda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\initialization.py", line 354, in initialize_components
    sn=sn, nb=nb, ssub=ssub, ssub_B=ssub_B, init_iter=init_iter, seed_method=seed_method)
  File "C:\Users\USER\.conda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\initialization.py", line 1304, in greedyROI_corr
    dview=None, dims=(d1, d2), **options['spatial_params'])
  File "C:\Users\USER\.conda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\spatial.py", line 240, in update_spatial_components
    parallel_result = list(map(regression_ipyparallel, pixel_groups))
  File "C:\Users\USER\.conda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\spatial.py", line 392, in regression_ipyparallel
    c = C[idxs_C[idx_px_from_0], :]
IndexError: index 5 is out of bounds for axis 0 with size 5
"""

The above exception was the direct cause of the following exception:

IndexError                                Traceback (most recent call last)
<ipython-input-16-595bc5cd7ebe> in <module>
      2 t1 = -time()
      3 cnm = cnmf.CNMF(n_processes=n_processes, dview=dview, params=opts)
----> 4 cnm.fit(images)
      5 t1 += time()

~\.conda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in fit(self, images, indices)
    604                     low_rank_background=self.params.get('patch', 'low_rank_background'),
    605                     del_duplicates=self.params.get('patch', 'del_duplicates'),
--> 606                     indices=indices)
    607 
    608             self.estimates.bl, self.estimates.c1, self.estimates.g, self.estimates.neurons_sn = None, None, None, None

~\.conda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\map_reduce.py in run_CNMF_patches(file_name, shape, params, gnb, dview, memory_fact, border_pix, low_rank_background, del_duplicates, indices)
    247     if dview is not None:
    248         if 'multiprocessing' in str(type(dview)):
--> 249             file_res = dview.map_async(cnmf_patches, args_in).get(4294967)
    250         else:
    251             try:

~\.conda\envs\caiman\lib\multiprocessing\pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

IndexError: index 5 is out of bounds for axis 0 with size 5

**Comment by SophiePinder** [comment] 2021-04-16 13:17
> @SophiePinder @j-friedrich Did you figure out a solution for this? I think I'm having the same/similar issue. It works well with the downloaded demo file but not with my data.
> 
> I also tried setting 'update_background_components': False (in cnmfe_dict, is this right?) but this didn't help.
> 
> I could also send you the file I'm trying to run, maybe there is an issue with that.
> 
> * **Tell us a bit about your setup**:
> 
> 1. Operating system (Linux/macOS/Windows):
>    Windows 10
> 2. Python version (3.x):
> 3. 3.7.10
> 4. Working environment (Python IDE/Jupyter Notebook/other):
>    Jupyter Notebook
> 5. Which of the demo scripts you're using for your analysis (if applicable):
>    demo_online_cnmfE.ipynb (with custom miniscope avi file)
> 6. CaImAn version*:
>    1.8.8
> 7. CaImAn installation process (`pip install .`/`pip install -e .`/conda):
>    conda
> 
> * **Describe the issue that you are experiencing**
>   as above
> * **Copy error log below**
> 
> RemoteTraceback Traceback (most recent call last)
> RemoteTraceback:
> """
> Traceback (most recent call last):
> File "C:\Users\USER.conda\envs\caiman\lib\multiprocessing\pool.py", line 121, in worker
> result = (True, func(*args, **kwds))
> File "C:\Users\USER.conda\envs\caiman\lib\multiprocessing\pool.py", line 44, in mapstar
> return list(map(*args))
> File "C:\Users\USER.conda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\map_reduce.py", line 137, in cnmf_patches
> cnm = cnm.fit(images)
> File "C:\Users\USER.conda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py", line 506, in fit
> self.initialize(Y)
> File "C:\Users\USER.conda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py", line 966, in initialize
> **self.params.get_group('init'))
> File "C:\Users\USER.conda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\initialization.py", line 354, in initialize_components
> sn=sn, nb=nb, ssub=ssub, ssub_B=ssub_B, init_iter=init_iter, seed_method=seed_method)
> File "C:\Users\USER.conda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\initialization.py", line 1304, in greedyROI_corr
> dview=None, dims=(d1, d2), **options['spatial_params'])
> File "C:\Users\USER.conda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\spatial.py", line 240, in update_spatial_components
> parallel_result = list(map(regression_ipyparallel, pixel_groups))
> File "C:\Users\USER.conda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\spatial.py", line 392, in regression_ipyparallel
> c = C[idxs_C[idx_px_from_0], :]
> IndexError: index 5 is out of bounds for axis 0 with size 5
> """
> 
> The above exception was the direct cause of the following exception:
> 
> IndexError Traceback (most recent call last)
> in
> 2 t1 = -time()
> 3 cnm = cnmf.CNMF(n_processes=n_processes, dview=dview, params=opts)
> ----> 4 cnm.fit(images)
> 5 t1 += time()
> 
> ~.conda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in fit(self, images, indices)
> 604 low_rank_background=self.params.get('patch', 'low_rank_background'),
> 605 del_duplicates=self.params.get('patch', 'del_duplicates'),
> --> 606 indices=indices)
> 607
> 608 self.estimates.bl, self.estimates.c1, self.estimates.g, self.estimates.neurons_sn = None, None, None, None
> 
> ~.conda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\map_reduce.py in run_CNMF_patches(file_name, shape, params, gnb, dview, memory_fact, border_pix, low_rank_background, del_duplicates, indices)
> 247 if dview is not None:
> 248 if 'multiprocessing' in str(type(dview)):
> --> 249 file_res = dview.map_async(cnmf_patches, args_in).get(4294967)
> 250 else:
> 251 try:
> 
> ~.conda\envs\caiman\lib\multiprocessing\pool.py in get(self, timeout)
> 655 return self._value
> 656 else:
> --> 657 raise self._value
> 658
> 659 def _set(self, i, obj):
> 
> IndexError: index 5 is out of bounds for axis 0 with size 5

@hahnjohannes Hi, sorry I can't be much help here. I don't have this problem anymore but i'm not sure how the problem was resolved, I just tried again on a different day and it worked. When I was struggling with this step I did try the above suggestions but it didn't make any difference. sorry I can't be anymore help

**Comment by hahnjohannes** [comment] 2021-05-18 12:15
I did a few tests and it seems that the rf parameter plays a role here. When I increase rf to the cnmfe runs without an error. For a single file (1000 frames) it worked with 75, when trying multiple (7) files at once it crashed again with 75 but worked with 100. 
I'm a bit confused how this influences the data / If there is a common principle here

**Comment by j-friedrich** [comment] 2021-11-19 14:37
Finally tracked down and fixed in dev.

**Closed by j-friedrich** 2021-11-19 14:37 UTC
